"""Generate every results table, in-text number and data figure of the manuscript
from results/*.json. Nothing in paper/generated/ is edited by hand.

Outputs
  paper/generated/macros.tex        \newcommand for every number quoted in the text
  paper/generated/tab_*.tex         table bodies (\input by paper/manuscript.tex)
  paper/figures/Fig4..Fig7.{pdf,tif}
Usage: python make_tables.py
"""
import json
import os

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
RES = os.path.join(HERE, "results")
GEN = os.path.join(HERE, "paper", "generated")
FIG = os.path.join(HERE, "paper", "figures")
SCN = ["S1", "S2", "S3"]
TASKS = ["binary", "multiclass"]
SCN_LABEL = {"S1": "S1 (UAV)", "S2": "S2 (AP)", "S3": "S3 (GCS)"}
MACRO_SCN = {"S1": "SOne", "S2": "STwo", "S3": "SThree"}
MACRO_TASK = {"binary": "Bin", "multiclass": "Multi"}
CRIT = [("task_aware", "Task-aware"), ("wcss_kneedle", "WCSS kneedle"), ("all_features", "All features")]


def load(sub=""):
    out = {}
    for s in SCN:
        for t in TASKS:
            p = os.path.join(RES, sub, f"{s}_{t}.json")
            if os.path.exists(p):
                with open(p) as fh:
                    out[(s, t)] = json.load(fh)
    return out


R = load()
RD = load("with_duplicates")
missing = [(s, t) for s in SCN for t in TASKS if (s, t) not in R]
if missing:
    raise SystemExit(f"missing results: {missing}")


def f4(x):
    return f"{x:.4f}"


def pct(x, d=2):
    return f"{100 * x:.{d}f}"


def i(x):
    return f"{int(x):,}"


def tex(s):
    return s.replace("_", r"\_").replace("&", r"\&").replace("%", r"\%")


def write(name, body):
    with open(os.path.join(GEN, name), "w") as fh:
        fh.write("% GENERATED by make_tables.py from results/*.json -- do not edit\n" + body)


def tabular(spec, header, rows):
    out = [r"\begin{tabular}{" + spec + "}", r"\hline", " & ".join(rf"\textbf{{{h}}}" for h in header) + r"\\ \thickhline"]
    out += [" & ".join(str(c) for c in r) + r"\\ \hline" for r in rows]
    out.append(r"\end{tabular}")
    return "\n".join(out) + "\n"


def cls(res, tag, name):
    for c in res["test"][tag]["per_class"]:
        if c["class"] == name:
            return c
    raise KeyError(name)


os.makedirs(GEN, exist_ok=True)
os.makedirs(FIG, exist_ok=True)

# ------------------------------------------------------------------ macros
M = {}
for (s, t), r in R.items():
    p = MACRO_SCN[s] + MACRO_TASK[t]
    sel = r["selection"]
    ta = r["test"]["task_aware"]
    M[p + "n"] = str(r["preprocessing"]["n_features_after_preprocessing"])
    M[p + "Kstar"] = str(sel["K_star"])
    M[p + "Khat"] = str(sel["K_hat_argmax"])
    M[p + "Kwcss"] = str(sel["K_wcss_kneedle"])
    M[p + "Red"] = f"{sel['reduction_pct']:.1f}"
    M[p + "CVFone"] = f4(sel["cv_f1_at_K_star"])
    M[p + "CVFoneAll"] = f4(sel["cv_f1_at_all_features"])
    M[p + "Acc"] = pct(ta["accuracy"])
    M[p + "BalAcc"] = pct(ta["balanced_accuracy"])
    M[p + "wF"] = pct(ta["weighted"]["f1"])
    M[p + "mF"] = pct(ta["macro"]["f1"])
    M[p + "AllwF"] = pct(r["test"]["all_features"]["weighted"]["f1"])
    M[p + "AllmF"] = pct(r["test"]["all_features"]["macro"]["f1"])
    M[p + "NTest"] = i(ta["n_test"])
    M[p + "NTrain"] = i(r["split"]["n_train"])
    M[p + "NSel"] = i(sel["n_selection_rows"])
    M[p + "SweepS"] = f"{sel['sweep_runtime_s']:.0f}"
    M[p + "WcssFeat"] = str(r["efficiency"]["wcss_kneedle"]["n_features"])
    M[p + "WcsswF"] = pct(r["test"]["wcss_kneedle"]["weighted"]["f1"])
    M[p + "WcssmF"] = pct(r["test"]["wcss_kneedle"]["macro"]["f1"])
    M[p + "NormTest"] = i(cls(r, "task_aware", "Normal")["support"])
    if t == "binary":
        bc = ta["binary_counts"]
        nor = cls(r, "task_aware", "Normal")
        for k in ["TP", "FP", "FN", "TN"]:
            M[p + k] = i(bc[k])
        M[p + "NormTest"] = i(nor["support"])
        M[p + "NormP"] = pct(nor["precision"], 1)
        M[p + "NormR"] = pct(nor["recall"], 1)
        M[p + "NormF"] = pct(nor["f1"], 1)
    pre = r["preprocessing"]
    if t == "multiclass":
        M[p + "RowsRaw"] = i(pre["n_rows_raw"])
        M[p + "RowsUsed"] = i(pre["n_rows_used"])
        M[p + "DupRows"] = i(pre["n_duplicate_rows"])
        M[p + "DupPct"] = f"{100 * pre['n_duplicate_rows'] / pre['n_rows_raw']:.1f}"
        M[p + "Conflict"] = i(pre["n_feature_vectors_with_conflicting_labels"])
        M[p + "ColsRaw"] = str(pre["n_columns_raw"])
        M[p + "NClasses"] = str(len(r["class_names"]))
        ab = r["ablation_cv"]
        for v, k in [("A_full", "AbA"), ("B_random_representative", "AbB"), ("C_all_features", "AbC"), ("D_no_smote", "AbD")]:
            M[p + k] = f4(ab[v]["mean"])
        ef = r["efficiency"]
        M[p + "TrainRed"] = f"{100 * (1 - ef['task_aware']['train_time_s'] / ef['all_features']['train_time_s']):.0f}"
loss = [100 * (R[(s, "multiclass")]["test"]["task_aware"]["macro"]["f1"] - R[(s, "multiclass")]["test"]["wcss_kneedle"]["macro"]["f1"]) for s in ["S1", "S2"]]
M["WcssLossMin"] = f"{min(loss):.1f}"
M["WcssLossMax"] = f"{max(loss):.1f}"
p3 = R[("S3", "multiclass")]["preprocessing"]
M["SThreeDoSRawPct"] = f"{100 * p3['class_counts_raw']['DoS'] / p3['n_rows_raw']:.1f}"
M["SThreeDoSUsedPct"] = f"{100 * p3['class_counts_used']['DoS'] / p3['n_rows_used']:.1f}"
M["NSmallerK"] = str(sum(R[k]["selection"]["K_star"] < R[k]["selection"]["K_hat_argmax"] for k in R))
M["NRuns"] = str(len(R))
M["SThreeDeauthTest"] = i(cls(R[("S3", "multiclass")], "task_aware", "De-authentication")["support"])
M["SThreeEvilTest"] = i(cls(R[("S3", "multiclass")], "task_aware", "Evil Twin")["support"])
M["SOneReconTest"] = i(cls(R[("S1", "multiclass")], "task_aware", "Reconnaissance")["support"])
M["SThreeOneNormPct"] = f"{100 / cls(R[('S3', 'binary')], 'task_aware', 'Normal')['support']:.1f}"
M["AbCMaxDiff"] = f"{max(abs(R[k]['ablation_cv']['C_all_features']['mean'] - R[k]['ablation_cv']['A_full']['mean']) for k in R):.4f}"
M["SweepMax"] = f"{max(R[k]['selection']['sweep_runtime_s'] for k in R):.0f}"
M["BinKstarMin"] = str(min(R[(s, "binary")]["selection"]["K_star"] for s in SCN))
M["BinKstarMax"] = str(max(R[(s, "binary")]["selection"]["K_star"] for s in SCN))
env = R[("S1", "multiclass")]["environment"]
M["EnvPython"] = env["python"]
M["EnvSklearn"] = env["scikit_learn"]
M["EnvImblearn"] = env["imbalanced_learn"]
M["EnvNumpy"] = env["numpy"]
M["EnvPandas"] = env["pandas"]
M["EnvCPU"] = str(env["cpu_count"])
proto = R[("S1", "multiclass")]["protocol"]
M["SelCap"] = i(proto["selection_sample_cap"])
M["MinPerClassSel"] = str(proto["min_per_class_selection"])
M["NFolds"] = str(proto["n_folds"])
M["KmeansInit"] = str(proto["kmeans_n_init"])
if len(RD) == len(R):
    for (s_, t_), rd in RD.items():
        p = MACRO_SCN[s_] + MACRO_TASK[t_] + "Dup"
        m = rd["test"]["task_aware"]
        M[p + "wF"] = pct(m["weighted"]["f1"])
        M[p + "mF"] = pct(m["macro"]["f1"])
        M[p + "Kstar"] = str(rd["selection"]["K_star"])
    M["DupMaxDiffSOneSTwo"] = f"{100 * max(abs(RD[(s_, t_)]['test']['task_aware']['weighted']['f1'] - R[(s_, t_)]['test']['task_aware']['weighted']['f1']) for s_ in ['S1', 'S2'] for t_ in TASKS):.2f}"
    dos = cls(RD[("S3", "multiclass")], "task_aware", "DoS")
    M["SThreeMultiDupDoSRecall"] = pct(dos["recall"], 1)
    M["SThreeMultiDupDoSTest"] = i(dos["support"])
    M["SThreeMultiDupNTest"] = i(RD[("S3", "multiclass")]["test"]["task_aware"]["n_test"])
dg_path = os.path.join(RES, "diagnostics.json")
if os.path.exists(dg_path):
    with open(dg_path) as fh:
        DG = json.load(fh)
    M["DgDoSVectors"] = i(DG["S3_distinct_DoS_vectors"])
    M["DgDoSConflict"] = i(DG["S3_conflicting_vectors_involving_DoS"])
    M["DgMisRows"] = i(DG["S3_withdup_misclassified_DoS_test_rows"])
    M["DgMisVectors"] = i(DG["S3_withdup_misclassified_DoS_distinct_vectors"])
    M["DgMisLargest"] = i(DG["S3_withdup_misclassified_DoS_largest_vector_count"])

write("macros.tex", "".join(rf"\newcommand{{\{k}}}{{{v}}}" + "\n" for k, v in sorted(M.items())))

# ------------------------------------------------------------------ tables
# Scenarios
rows = []
for s in SCN:
    r = R[(s, "multiclass")]
    pre = r["preprocessing"]
    rows.append([SCN_LABEL[s], r["scenario_name"], pre["n_columns_raw"], pre["n_features_after_preprocessing"],
                 i(pre["n_rows_raw"]), i(pre["n_rows_used"]), i(pre["n_feature_vectors_with_conflicting_labels"])])
write("tab_scenarios.tex", tabular("|l|l|r|r|r|r|r|",
      ["Scenario", "Compromise point", "Raw feat.", "After P1--P6", "Raw rows", "Unique rows", "Conflicting"], rows))

# Class distribution (raw and after duplicate removal)
classes = []
for s in SCN:
    for c in R[(s, "multiclass")]["preprocessing"]["class_counts_raw"]:
        if c not in classes:
            classes.append(c)
order = ["Normal", "DDoS", "DoS", "UDP Flooding", "ICMP Flooding", "De-authentication", "Brute-Force",
         "Evil Twin", "Scanning", "Reconnaissance", "GPS Jamming", "Fake Landing", "MITM", "Replay"]
classes = [c for c in order if c in classes] + [c for c in classes if c not in order]
rows = []
for c in classes:
    row = [c]
    for s in SCN:
        pre = R[(s, "multiclass")]["preprocessing"]
        raw = pre["class_counts_raw"].get(c)
        used = pre["class_counts_used"].get(c)
        row += [i(raw) if raw else "---", i(used) if used else "---"]
    rows.append(row)
tot = ["Total"]
for s in SCN:
    pre = R[(s, "multiclass")]["preprocessing"]
    tot += [i(pre["n_rows_raw"]), i(pre["n_rows_used"])]
rows.append(tot)
write("tab_classes.tex", tabular("|l|r|r|r|r|r|r|",
      ["Class", "S1 raw", "S1 unique", "S2 raw", "S2 unique", "S3 raw", "S3 unique"], rows))

# Elbow summary
rows = []
for s in SCN:
    for t in TASKS:
        sel = R[(s, t)]["selection"]
        rows.append([SCN_LABEL[s], t.capitalize(), R[(s, t)]["preprocessing"]["n_features_after_preprocessing"],
                     sel["K_star"], sel["K_hat_argmax"], sel["K_wcss_kneedle"],
                     f"{sel['reduction_pct']:.1f}", f4(sel["cv_f1_at_K_star"]), f4(sel["cv_f1_at_all_features"])])
write("tab_elbow.tex", tabular("|l|l|r|r|r|r|r|r|r|",
      ["Scenario", "Task", "$n$", "$K^{*}$", r"$\hat{K}$", "$K_{\\mathrm{WCSS}}$", "Red. (\\%)",
       "CV wF1 at $K^{*}$", "CV wF1 all $n$"], rows))

# Selected features (multiclass), top 10 per scenario
rows = []
for s in SCN:
    feats = R[(s, "multiclass")]["selection"]["selected_features"]
    for k, f in enumerate(feats[:10], 1):
        rows.append([SCN_LABEL[s] if k == 1 else "", k, r"\texttt{" + tex(f["feature"]) + "}",
                     f4(f["abs_rho"]), f["cluster_size"]])
write("tab_features.tex", tabular("|l|r|l|r|r|", ["Scenario", "Rk", "Feature", r"$|\rho|$", "Cluster size"], rows))

# Binary detection
rows = []
for s in SCN:
    r = R[(s, "binary")]
    for tag, lab in CRIT:
        m = r["test"][tag]
        nor = cls(r, tag, "Normal")
        bc = m["binary_counts"]
        rows.append([SCN_LABEL[s], lab, r["efficiency"][tag]["n_features"], f4(m["accuracy"]), f4(m["balanced_accuracy"]),
                     f4(m["weighted"]["f1"]), f4(m["macro"]["f1"]), f4(nor["precision"]), f4(nor["recall"]),
                     i(nor["support"]), i(bc["FP"]), i(bc["FN"])])
write("tab_binary.tex", tabular("|l|l|r|r|r|r|r|r|r|r|r|r|",
      ["Scenario", "Criterion", "Feat.", "Acc.", "Bal. acc.", "wF1", "Macro F1", "Normal P", "Normal R",
       "Normal $n$", "FP", "FN"], rows))

# Multi-class aggregate
rows = []
for s in SCN:
    r = R[(s, "multiclass")]
    for tag, lab in CRIT:
        m = r["test"][tag]
        rows.append([SCN_LABEL[s], lab, r["efficiency"][tag]["n_features"], f4(m["accuracy"]), f4(m["balanced_accuracy"]),
                     f4(m["weighted"]["precision"]), f4(m["weighted"]["recall"]), f4(m["weighted"]["f1"]), f4(m["macro"]["f1"])])
write("tab_multiclass.tex", tabular("|l|l|r|r|r|r|r|r|r|",
      ["Scenario", "Criterion", "Feat.", "Acc.", "Bal. acc.", "wPrec", "wRec", "wF1", "Macro F1"], rows))

# Per-class (task-aware, multiclass)
for s in SCN:
    m = R[(s, "multiclass")]["test"]["task_aware"]
    rows = [[c["class"], f4(c["precision"]), f4(c["recall"]), f4(c["f1"]), i(c["support"])] for c in m["per_class"]]
    rows.append(["Macro avg", f4(m["macro"]["precision"]), f4(m["macro"]["recall"]), f4(m["macro"]["f1"]), i(m["n_test"])])
    rows.append(["Weighted avg", f4(m["weighted"]["precision"]), f4(m["weighted"]["recall"]), f4(m["weighted"]["f1"]), i(m["n_test"])])
    write(f"tab_perclass_{s}.tex", tabular("|l|r|r|r|r|", ["Class", "Precision", "Recall", "F1", "Support"], rows))

# Ablation (5-fold CV, multiclass and binary)
VAR = [("A_full", "A: Full framework"), ("B_random_representative", "B: Random representative"),
       ("C_all_features", "C: No elbow (all $n$)"), ("D_no_smote", "D: No SMOTE")]
for t in TASKS:
    rows = []
    for v, lab in VAR:
        row = [lab]
        for s in SCN:
            ab = R[(s, t)]["ablation_cv"]
            d = ab[v]["mean"] - ab["A_full"]["mean"]
            row += [f"{ab[v]['mean']:.4f} $\\pm$ {ab[v]['sd']:.4f}", "---" if v == "A_full" else f"{d:+.4f}".replace("-", "$-$")]
        rows.append(row)
    write(f"tab_ablation_{t}.tex", tabular("|l|l|r|l|r|l|r|",
          ["Variant", "S1 wF1", "S1 $\\Delta$", "S2 wF1", "S2 $\\Delta$", "S3 wF1", "S3 $\\Delta$"], rows))

# Efficiency (multiclass)
rows = []
for s in SCN:
    r = R[(s, "multiclass")]
    for tag, lab in CRIT:
        e = r["efficiency"][tag]
        rows.append([SCN_LABEL[s], lab, e["n_features"], f"{e['train_time_s']:.2f}", f"{e['inference_ms_per_sample']:.5f}",
                     f"{e['model_size_kb']:.0f}", e["tree_depth"], i(e["tree_leaves"])])
write("tab_efficiency.tex", tabular("|l|l|r|r|r|r|r|r|",
      ["Scenario", "Configuration", "Feat.", "Train (s)", "Inference (ms)", "Model (KB)", "Depth", "Leaves"], rows))

# Sensitivity: with vs without duplicate removal
if RD:
    rows = []
    for s in SCN:
        for t in TASKS:
            if (s, t) not in RD:
                continue
            a, b = R[(s, t)], RD[(s, t)]
            ma, mb = a["test"]["task_aware"], b["test"]["task_aware"]
            rows.append([SCN_LABEL[s], t.capitalize(), i(a["preprocessing"]["n_rows_used"]), a["selection"]["K_star"],
                         f4(ma["weighted"]["f1"]), f4(ma["macro"]["f1"]),
                         i(b["preprocessing"]["n_rows_used"]), b["selection"]["K_star"],
                         f4(mb["weighted"]["f1"]), f4(mb["macro"]["f1"])])
    body = tabular("|l|l|r|r|r|r|r|r|r|r|",
                   ["Scenario", "Task", "Rows", "$K^{*}$", "wF1", "Macro F1", "Rows", "$K^{*}$", "wF1", "Macro F1"], rows)
    group = (r"\multicolumn{2}{|c|}{} & \multicolumn{4}{c|}{\textbf{Duplicates removed (main)}} & "
             r"\multicolumn{4}{c|}{\textbf{Duplicates kept}}\\ \hline" + "\n")
    body = body.replace("\\hline\n", "\\hline\n" + group, 1)
    write("tab_duplicates.tex", body)

# ------------------------------------------------------------------ figures
plt.rcParams.update({"font.size": 8, "axes.titlesize": 9, "font.family": "DejaVu Sans"})
COL = {"S1": "#1f5a96", "S2": "#b8433a", "S3": "#3a8a4a"}


PLOS_DPI = 300
PLOS_MAX_W_IN = 7.5  # PLOS: figure width 2.63-7.5 in, height <= 8.75 in


def save(fig, name):
    fig.savefig(os.path.join(FIG, name + ".pdf"), bbox_inches="tight")
    tif = os.path.join(FIG, name + ".tif")
    fig.savefig(tif, dpi=PLOS_DPI, bbox_inches="tight",
                pil_kwargs={"compression": "tiff_lzw"})
    plt.close(fig)
    # bbox_inches="tight" can push the saved width past the figsize, and the Agg
    # backend writes RGBA. PLOS requires RGB/grayscale within 7.5 in, so flatten
    # the alpha channel onto white and scale down if the bounding box overran.
    from PIL import Image
    im = Image.open(tif)
    im.load()
    if im.mode in ("RGBA", "LA", "P"):
        rgba = im.convert("RGBA")
        flat = Image.new("RGB", rgba.size, (255, 255, 255))
        flat.paste(rgba, mask=rgba.split()[-1])
        im = flat
    max_px = int(PLOS_MAX_W_IN * PLOS_DPI)
    if im.size[0] > max_px:
        h = round(im.size[1] * max_px / im.size[0])
        im = im.resize((max_px, h), Image.LANCZOS)
    im.save(tif, compression="tiff_lzw", dpi=(PLOS_DPI, PLOS_DPI))


# Fig4: class distribution (unique rows) per scenario, log scale
fig, axes = plt.subplots(1, 3, figsize=(7.5, 3.0))
for ax, s in zip(axes, SCN):
    cc = R[(s, "multiclass")]["preprocessing"]["class_counts_used"]
    names = [c for c in classes if c in cc]
    ax.barh(range(len(names)), [cc[c] for c in names], color=COL[s])
    ax.set_xscale("log")
    ax.set_title(SCN_LABEL[s])
    ax.set_xlabel("Unique flows (log scale)")
    ax.set_yticks(range(len(names)))
    ax.set_yticklabels(names)
    ax.invert_yaxis()
fig.tight_layout()
save(fig, "Fig4")

# Fig5: CV weighted F1 vs K with SE band, K* and K_hat marked
fig, axes = plt.subplots(1, 2, figsize=(7.5, 2.9), sharey=False)
for ax, t in zip(axes, TASKS):
    for s in SCN:
        sel = R[(s, t)]["selection"]
        K, m, se = sel["K"], sel["cv_f1_mean"], sel["cv_f1_se"]
        ax.plot(K, m, color=COL[s], lw=1.2, label=SCN_LABEL[s])
        ax.fill_between(K, [a - b for a, b in zip(m, se)], [a + b for a, b in zip(m, se)], color=COL[s], alpha=0.2, lw=0)
        ks = sel["K_star"]
        ax.plot([ks], [m[K.index(ks)]], "o", color=COL[s], ms=5, mfc="white", mew=1.4)
    ax.set_xlabel("Cluster count $K$")
    ax.set_ylabel("5-fold CV weighted F1")
    ax.set_title(("A: binary" if t == "binary" else "B: multi-class"))
    ax.grid(alpha=0.3)
    ax.legend(loc="lower right", frameon=False)
fig.tight_layout()
save(fig, "Fig5")

# Fig6: |rho| of the selected features (multiclass)
fig, axes = plt.subplots(1, 3, figsize=(7.5, 3.2))
for ax, s, lab in zip(axes, SCN, "ABC"):
    feats = R[(s, "multiclass")]["selection"]["selected_features"]
    ax.barh(range(len(feats)), [f["abs_rho"] for f in feats], color=COL[s])
    ax.set_yticks(range(len(feats)))
    ax.set_yticklabels([f["feature"] for f in feats], fontsize=6)
    ax.invert_yaxis()
    ax.set_xlabel(r"$|\rho|$ with label")
    ax.set_title(f"{lab}: {SCN_LABEL[s]}, {len(feats)} features")
fig.tight_layout()
save(fig, "Fig6")

# Fig7: binary vs multi-class, weighted and macro F1 on the sealed test set
fig, ax = plt.subplots(figsize=(6.0, 2.8))
labels, wv, mv = [], [], []
for s in SCN:
    for t in TASKS:
        m = R[(s, t)]["test"]["task_aware"]
        labels.append(f"{s}\n{'Bin' if t == 'binary' else 'MC'}")
        wv.append(m["weighted"]["f1"])
        mv.append(m["macro"]["f1"])
x = range(len(labels))
ax.bar([k - 0.2 for k in x], wv, 0.4, label="Weighted F1", color="#1f5a96")
ax.bar([k + 0.2 for k in x], mv, 0.4, label="Macro F1", color="#d99a3a")
ax.set_xticks(list(x))
ax.set_xticklabels(labels)
ax.set_ylim(0, 1.05)
ax.set_ylabel("Sealed-test score")
ax.legend(frameon=False, loc="lower center", bbox_to_anchor=(0.5, 1.0), ncol=2)
ax.grid(axis="y", alpha=0.3)
fig.tight_layout()
save(fig, "Fig7")

# Response letter: {{Macro}} placeholders filled from the same macros
import re  # noqa: E402
tpl = os.path.join(HERE, "paper", "response_letter.template.md")
if os.path.exists(tpl):
    with open(tpl) as fh:
        txt = fh.read()
    txt = re.sub(r"\{\{(\w+)\}\}", lambda mo: M[mo.group(1)], txt)
    with open(os.path.join(HERE, "paper", "response_letter.md"), "w") as fh:
        fh.write(txt)

# Flat manuscript for journal upload: every \input{generated/...} inlined
ms = os.path.join(HERE, "paper", "manuscript.tex")
if os.path.exists(ms):
    with open(ms) as fh:
        src = fh.read()

    def inline(mo):
        with open(os.path.join(HERE, "paper", mo.group(1) + ".tex")) as g:
            return "".join(ln for ln in g if not ln.startswith("% GENERATED")).rstrip("\n")
    flat = re.sub(r"\\input\{(generated/[\w]+)\}", inline, src)
    with open(os.path.join(HERE, "paper", "manuscript_flat.tex"), "w") as fh:
        fh.write("% Flattened by make_tables.py from manuscript.tex -- edit manuscript.tex instead\n" + flat)

print(f"wrote {len(M)} macros, tables and figures to {GEN} and {FIG}")
